name: neat_state
description: Nice and simple app global state
version: 0.0.1
homepage: https://github.com/sla-000/neat_state

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
